### ISSUE TITLE
Total cost in Geronimo is not limited

### ISSUE THREAD

**Issue by ghost** [speaking-clubs-nizhny/speaking-clubs-nizhny.github.io#1]
I've found a small inaccuracy for ESC. Total cost in Geronimo is not limited to 300 RUB: "2.5 rub/minute (up to 300 rub)" is not true, at least now

**Comment by quasilyte** [comment]
Correct. Need to update the info.
Thanks!

**Comment by quasilyte** [comment]
Fixed.
